months = set(["January","February","March","April","May","June"])
print("Printing orignal set...")
print(months)
print("Adding new elements...")
months.add("July")
months.add("August")
print(months)
print("Adding more than one elements together...")
months.update(["September","October","November","December"])
print(months)