months = set(["January","February","March","April","May","June","July","August","September","October","November","December"])
print("Printing orignal set...")
print(months)
print("Deleting only one element using remove...")
months.remove("February")
print(months)
print("Deleting only one element using discard...")
months.discard("March")
print(months)
months.discard("March")
#months.remove("March")
print("Removing an element which is not present in the set gives error, while discard does not...")